/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\hongblog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3cb4c92f",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cb4c92f").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-01366f9f",
    path: "/git/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01366f9f").then(next)
    },
  },
  {
    name: "v-5c299c85",
    path: "/git/git%E6%8E%A8%E9%80%81%E5%88%B0%E8%BF%9C%E7%A8%8B%E7%9A%84%E4%BB%93%E5%BA%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c299c85").then(next)
    },
  },
  {
    path: "/git/git推送到远程的仓库.html",
    redirect: "/git/git%E6%8E%A8%E9%80%81%E5%88%B0%E8%BF%9C%E7%A8%8B%E7%9A%84%E4%BB%93%E5%BA%93.html"
  },
  {
    path: "/git/git推送到远程的仓库.html",
    redirect: "/git/git%E6%8E%A8%E9%80%81%E5%88%B0%E8%BF%9C%E7%A8%8B%E7%9A%84%E4%BB%93%E5%BA%93.html"
  },
  {
    name: "v-42b08104",
    path: "/java/Mybatis/mybatis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42b08104").then(next)
    },
  },
  {
    name: "v-738875e6",
    path: "/java/Mybatis/select01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-738875e6").then(next)
    },
  },
  {
    name: "v-ebb3d274",
    path: "/java/Mybatis/select02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebb3d274").then(next)
    },
  },
  {
    name: "v-07adac94",
    path: "/java/javaSEBase/day14-IO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07adac94").then(next)
    },
  },
  {
    name: "v-1488315e",
    path: "/java/javaSEBase/day15-IO01%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1488315e").then(next)
    },
  },
  {
    path: "/java/javaSEBase/day15-IO01流.html",
    redirect: "/java/javaSEBase/day15-IO01%E6%B5%81.html"
  },
  {
    path: "/java/javaSEBase/day15-IO01流.html",
    redirect: "/java/javaSEBase/day15-IO01%E6%B5%81.html"
  },
  {
    name: "v-2d58845e",
    path: "/java/javaSEBase/day15-IO02%E8%BD%AC%E6%8D%A2%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d58845e").then(next)
    },
  },
  {
    path: "/java/javaSEBase/day15-IO02转换流.html",
    redirect: "/java/javaSEBase/day15-IO02%E8%BD%AC%E6%8D%A2%E6%B5%81.html"
  },
  {
    path: "/java/javaSEBase/day15-IO02转换流.html",
    redirect: "/java/javaSEBase/day15-IO02%E8%BD%AC%E6%8D%A2%E6%B5%81.html"
  },
  {
    name: "v-20d60fe0",
    path: "/java/javaSEBase/day15-IO03%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20d60fe0").then(next)
    },
  },
  {
    path: "/java/javaSEBase/day15-IO03对象操作流.html",
    redirect: "/java/javaSEBase/day15-IO03%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C%E6%B5%81.html"
  },
  {
    path: "/java/javaSEBase/day15-IO03对象操作流.html",
    redirect: "/java/javaSEBase/day15-IO03%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C%E6%B5%81.html"
  },
  {
    name: "v-28c21038",
    path: "/java/javaSEBase/day15-IO04Properties%E9%9B%86%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28c21038").then(next)
    },
  },
  {
    path: "/java/javaSEBase/day15-IO04Properties集合.html",
    redirect: "/java/javaSEBase/day15-IO04Properties%E9%9B%86%E5%90%88.html"
  },
  {
    path: "/java/javaSEBase/day15-IO04Properties集合.html",
    redirect: "/java/javaSEBase/day15-IO04Properties%E9%9B%86%E5%90%88.html"
  },
  {
    name: "v-6c85b54c",
    path: "/java/javaSEBase/java.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c85b54c").then(next)
    },
  },
  {
    name: "v-40d90282",
    path: "/network/network01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40d90282").then(next)
    },
  },
  {
    name: "v-557ebcd4",
    path: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/01docsify.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-557ebcd4").then(next)
    },
  },
  {
    path: "/软件资源/01docsify.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/01docsify.html"
  },
  {
    path: "/软件资源/01docsify.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/01docsify.html"
  },
  {
    name: "v-63361320",
    path: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/English_syntax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63361320").then(next)
    },
  },
  {
    path: "/软件资源/English_syntax.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/English_syntax.html"
  },
  {
    path: "/软件资源/English_syntax.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/English_syntax.html"
  },
  {
    name: "v-8ba33ae4",
    path: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/SetTitle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ba33ae4").then(next)
    },
  },
  {
    path: "/软件资源/vuepress怎么玩/SetTitle.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/SetTitle.html"
  },
  {
    path: "/软件资源/vuepress怎么玩/SetTitle.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/SetTitle.html"
  },
  {
    name: "v-021585d8",
    path: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/Writing_rules.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-021585d8").then(next)
    },
  },
  {
    path: "/软件资源/vuepress怎么玩/Writing_rules.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/Writing_rules.html"
  },
  {
    path: "/软件资源/vuepress怎么玩/Writing_rules.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/Writing_rules.html"
  },
  {
    name: "v-04d9f279",
    path: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04d9f279").then(next)
    },
  },
  {
    path: "/软件资源/软件资源.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90.html"
  },
  {
    path: "/软件资源/软件资源.html",
    redirect: "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90.html"
  },
  {
    name: "v-34a4cb9c",
    path: "/%E8%BF%90%E7%BB%B4/windows/cmd.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34a4cb9c").then(next)
    },
  },
  {
    path: "/运维/windows/cmd.html",
    redirect: "/%E8%BF%90%E7%BB%B4/windows/cmd.html"
  },
  {
    path: "/运维/windows/cmd.html",
    redirect: "/%E8%BF%90%E7%BB%B4/windows/cmd.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]