/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "匆匆趣玩",
  "description": "分享各类资源、教程、黑科技软件、工具等等",
  "base": "/triggergun/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.svg"
      }
    ]
  ],
  "pages": [
    {
      "title": "vuepress部署到github上",
      "frontmatter": {},
      "regularPath": "/git/git.html",
      "relativePath": "git/git.md",
      "key": "v-01366f9f",
      "path": "/git/git.html",
      "headers": [
        {
          "level": 2,
          "title": "第一步：打包",
          "slug": "第一步-打包"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "logo.svg",
        "heroText": "一个分享各类资源的地方",
        "tagline": "公众号：资料分享大师",
        "actionText": "查看资源 →",
        "actionLink": "/软件资源/软件资源",
        "features": [
          {
            "title": "人生苦短",
            "details": "洗手的时候，日子从水盆里过去；吃饭的时候，日子从碗里过去。八千的日子已经从我手中溜去"
          },
          {
            "title": "黑科技软件",
            "details": "主要分享一些实用性的工具类、影视类、音乐类等等各种软件，均由互联网大佬提供。"
          },
          {
            "title": "教程资源",
            "details": "分享各类教程，包括编程、各类证书考试资源等等，本网站所有教程资源均来自互联网，若涉及侵权立马删除！"
          }
        ],
        "footer": "匆匆趣玩 | 资料分享大师"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3cb4c92f",
      "path": "/",
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "git推送到远程的仓库",
      "frontmatter": {},
      "regularPath": "/git/git%E6%8E%A8%E9%80%81%E5%88%B0%E8%BF%9C%E7%A8%8B%E7%9A%84%E4%BB%93%E5%BA%93.html",
      "relativePath": "git/git推送到远程的仓库.md",
      "key": "v-5c299c85",
      "path": "/git/git%E6%8E%A8%E9%80%81%E5%88%B0%E8%BF%9C%E7%A8%8B%E7%9A%84%E4%BB%93%E5%BA%93.html",
      "headers": [
        {
          "level": 2,
          "title": "git推送到远程的仓库",
          "slug": "git推送到远程的仓库"
        },
        {
          "level": 2,
          "title": "vuepress更新文章并推送到git",
          "slug": "vuepress更新文章并推送到git"
        },
        {
          "level": 3,
          "title": "步骤一：",
          "slug": "步骤一"
        },
        {
          "level": 3,
          "title": "步骤二：上传到git上。",
          "slug": "步骤二-上传到git上。"
        },
        {
          "level": 3,
          "title": "步骤三：关联远程的仓库。",
          "slug": "步骤三-关联远程的仓库。"
        },
        {
          "level": 3,
          "title": "步骤四：强制推送到git。",
          "slug": "步骤四-强制推送到git。"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "Mybaits配置",
      "frontmatter": {},
      "regularPath": "/java/Mybatis/mybatis.html",
      "relativePath": "java/Mybatis/mybatis.md",
      "key": "v-42b08104",
      "path": "/java/Mybatis/mybatis.html",
      "headers": [
        {
          "level": 2,
          "title": "springboot整合mybaits",
          "slug": "springboot整合mybaits"
        },
        {
          "level": 3,
          "title": "第1步：导入maven坐标",
          "slug": "第1步-导入maven坐标"
        },
        {
          "level": 3,
          "title": "第2步：springboot配置文件",
          "slug": "第2步-springboot配置文件"
        },
        {
          "level": 3,
          "title": "第3步：注入数据源对象给spring",
          "slug": "第3步-注入数据源对象给spring"
        },
        {
          "level": 2,
          "title": "idea连接数据库",
          "slug": "idea连接数据库"
        },
        {
          "level": 3,
          "title": "数据库sql文件",
          "slug": "数据库sql文件"
        },
        {
          "level": 2,
          "title": "生成MyBatis各种文件",
          "slug": "生成mybatis各种文件"
        },
        {
          "level": 2,
          "title": "测试",
          "slug": "测试"
        },
        {
          "level": 2,
          "title": "生成代码是什么",
          "slug": "生成代码是什么"
        },
        {
          "level": 3,
          "title": "添加班级信息",
          "slug": "添加班级信息"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "案例一：查询列表数据",
      "frontmatter": {},
      "regularPath": "/java/Mybatis/select01.html",
      "relativePath": "java/Mybatis/select01.md",
      "key": "v-738875e6",
      "path": "/java/Mybatis/select01.html",
      "headers": [
        {
          "level": 2,
          "title": "业务场景描述",
          "slug": "业务场景描述"
        },
        {
          "level": 2,
          "title": "关系分析",
          "slug": "关系分析"
        },
        {
          "level": 2,
          "title": "第一步：查询结果映射",
          "slug": "第一步-查询结果映射"
        },
        {
          "level": 2,
          "title": "第二步：编写查询语句",
          "slug": "第二步-编写查询语句"
        },
        {
          "level": 2,
          "title": "第三步：查询条件",
          "slug": "第三步-查询条件"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "案例二：企业门户查询",
      "frontmatter": {},
      "regularPath": "/java/Mybatis/select02.html",
      "relativePath": "java/Mybatis/select02.md",
      "key": "v-ebb3d274",
      "path": "/java/Mybatis/select02.html",
      "headers": [
        {
          "level": 2,
          "title": "业务需求",
          "slug": "业务需求"
        },
        {
          "level": 2,
          "title": "门户查询条件",
          "slug": "门户查询条件"
        },
        {
          "level": 2,
          "title": "条件查询列表",
          "slug": "条件查询列表"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "代理（proxy）",
      "frontmatter": {},
      "regularPath": "/java/designModel/02%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "java/designModel/02动态代理模式.md",
      "key": "v-7350a031",
      "path": "/java/designModel/02%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "静态代理（static proxy）",
          "slug": "静态代理-static-proxy"
        },
        {
          "level": 2,
          "title": "JDk动态代理",
          "slug": "jdk动态代理"
        },
        {
          "level": 3,
          "title": "1）创建代理人接口",
          "slug": "_1-创建代理人接口"
        },
        {
          "level": 3,
          "title": "2）创建实现代理人接口的类",
          "slug": "_2-创建实现代理人接口的类"
        },
        {
          "level": 3,
          "title": "3）创建代理类",
          "slug": "_3-创建代理类"
        },
        {
          "level": 3,
          "title": "4）实现InvocationHandler接口",
          "slug": "_4-实现invocationhandler接口"
        },
        {
          "level": 3,
          "title": "编写测试类",
          "slug": "编写测试类"
        },
        {
          "level": 2,
          "title": "cglib与jdk动态代理工厂",
          "slug": "cglib与jdk动态代理工厂"
        },
        {
          "level": 3,
          "title": "第一步：创建找房子代理的接口",
          "slug": "第一步-创建找房子代理的接口"
        },
        {
          "level": 3,
          "title": "第二步：创建代理实现类",
          "slug": "第二步-创建代理实现类"
        },
        {
          "level": 3,
          "title": "第三步：创建代理工厂类",
          "slug": "第三步-创建代理工厂类"
        },
        {
          "level": 3,
          "title": "jdk动态代理的测试用例",
          "slug": "jdk动态代理的测试用例"
        },
        {
          "level": 3,
          "title": "cglib动态代理的测试用例",
          "slug": "cglib动态代理的测试用例"
        },
        {
          "level": 2,
          "title": "JDK动态代理的UML图",
          "slug": "jdk动态代理的uml图"
        }
      ],
      "lastUpdated": "8/5/2023, 10:41:09 PM",
      "lastUpdatedTimestamp": 1691304069000
    },
    {
      "title": "组装者设计模式",
      "frontmatter": {},
      "regularPath": "/java/designModel/AssemblerDesignPattern.html",
      "relativePath": "java/designModel/AssemblerDesignPattern.md",
      "key": "v-7b719b06",
      "path": "/java/designModel/AssemblerDesignPattern.html",
      "headers": [
        {
          "level": 2,
          "title": "需求：组装电脑",
          "slug": "需求-组装电脑"
        },
        {
          "level": 2,
          "title": "第一步：创建电脑类",
          "slug": "第一步-创建电脑类"
        },
        {
          "level": 2,
          "title": "第二步：创建组装者类",
          "slug": "第二步-创建组装者类"
        },
        {
          "level": 2,
          "title": "第三步：编写测试实例",
          "slug": "第三步-编写测试实例"
        },
        {
          "level": 2,
          "title": "UML类图",
          "slug": "uml类图"
        }
      ],
      "lastUpdated": "8/5/2023, 1:34:13 AM",
      "lastUpdatedTimestamp": 1691228053000
    },
    {
      "title": "1.字节流",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/day14-IO.html",
      "relativePath": "java/javaSEBase/day14-IO.md",
      "key": "v-07adac94",
      "path": "/java/javaSEBase/day14-IO.html",
      "headers": [
        {
          "level": 2,
          "title": "1.字节流",
          "slug": "_1-字节流"
        },
        {
          "level": 3,
          "title": "1.1 IO流概述和分类【理解】",
          "slug": "_1-1-io流概述和分类【理解】"
        },
        {
          "level": 3,
          "title": "1.2字节流写数据【应用】",
          "slug": "_1-2字节流写数据【应用】"
        },
        {
          "level": 3,
          "title": "1.3字节流写数据的三种方式【应用】",
          "slug": "_1-3字节流写数据的三种方式【应用】"
        },
        {
          "level": 3,
          "title": "1.4字节流写数据的两个小问题【应用】",
          "slug": "_1-4字节流写数据的两个小问题【应用】"
        },
        {
          "level": 3,
          "title": "1.5字节流写数据加异常处理【应用】",
          "slug": "_1-5字节流写数据加异常处理【应用】"
        },
        {
          "level": 3,
          "title": "1.6字节流读数据(一次读一个字节数据)【应用】",
          "slug": "_1-6字节流读数据-一次读一个字节数据-【应用】"
        },
        {
          "level": 3,
          "title": "1.7字节流复制文件【应用】",
          "slug": "_1-7字节流复制文件【应用】"
        },
        {
          "level": 3,
          "title": "1.8字节流读数据(一次读一个字节数组数据)【应用】",
          "slug": "_1-8字节流读数据-一次读一个字节数组数据-【应用】"
        },
        {
          "level": 3,
          "title": "1.9字节流复制文件【应用】",
          "slug": "_1-9字节流复制文件【应用】"
        },
        {
          "level": 2,
          "title": "2.字节缓冲流",
          "slug": "_2-字节缓冲流"
        },
        {
          "level": 3,
          "title": "2.1字节缓冲流构造方法【应用】",
          "slug": "_2-1字节缓冲流构造方法【应用】"
        },
        {
          "level": 3,
          "title": "2.2字节缓冲流复制视频【应用】",
          "slug": "_2-2字节缓冲流复制视频【应用】"
        },
        {
          "level": 2,
          "title": "3.字符流",
          "slug": "_3-字符流"
        },
        {
          "level": 3,
          "title": "3.1为什么会出现字符流【理解】",
          "slug": "_3-1为什么会出现字符流【理解】"
        },
        {
          "level": 3,
          "title": "3.2编码表【理解】",
          "slug": "_3-2编码表【理解】"
        },
        {
          "level": 3,
          "title": "3.3字符串中的编码解码问题【应用】",
          "slug": "_3-3字符串中的编码解码问题【应用】"
        },
        {
          "level": 3,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "1.字符流",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/day15-IO01%E6%B5%81.html",
      "relativePath": "java/javaSEBase/day15-IO01流.md",
      "key": "v-1488315e",
      "path": "/java/javaSEBase/day15-IO01%E6%B5%81.html",
      "headers": [
        {
          "level": 2,
          "title": "1.字符流",
          "slug": "_1-字符流"
        },
        {
          "level": 2,
          "title": "1.1为什么会出现字符流【理解】",
          "slug": "_1-1为什么会出现字符流【理解】"
        },
        {
          "level": 2,
          "title": "1.2编码表【理解】",
          "slug": "_1-2编码表【理解】"
        },
        {
          "level": 2,
          "title": "1.3字符串中的编码解码问题【应用】",
          "slug": "_1-3字符串中的编码解码问题【应用】"
        },
        {
          "level": 2,
          "title": "1.4字符流写数据【应用】",
          "slug": "_1-4字符流写数据【应用】"
        },
        {
          "level": 2,
          "title": "1.5字符流读数据【应用】",
          "slug": "_1-5字符流读数据【应用】"
        },
        {
          "level": 2,
          "title": "1.6字符流用户注册案例【应用】",
          "slug": "_1-6字符流用户注册案例【应用】"
        },
        {
          "level": 2,
          "title": "1.7字符缓冲流【应用】",
          "slug": "_1-7字符缓冲流【应用】"
        },
        {
          "level": 2,
          "title": "1.8字符缓冲流特有功能【应用】",
          "slug": "_1-8字符缓冲流特有功能【应用】"
        },
        {
          "level": 2,
          "title": "1.9字符缓冲流操作文件中数据排序案例【应用】",
          "slug": "_1-9字符缓冲流操作文件中数据排序案例【应用】"
        },
        {
          "level": 2,
          "title": "1.10IO流小结【理解】",
          "slug": "_1-10io流小结【理解】"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "2.转换流",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/day15-IO02%E8%BD%AC%E6%8D%A2%E6%B5%81.html",
      "relativePath": "java/javaSEBase/day15-IO02转换流.md",
      "key": "v-2d58845e",
      "path": "/java/javaSEBase/day15-IO02%E8%BD%AC%E6%8D%A2%E6%B5%81.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1字符流中和编码解码问题相关的两个类【理解】",
          "slug": "_2-1字符流中和编码解码问题相关的两个类【理解】"
        },
        {
          "level": 2,
          "title": "2.2转换流读写数据【应用】",
          "slug": "_2-2转换流读写数据【应用】"
        },
        {
          "level": 2,
          "title": "需求假设",
          "slug": "需求假设"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "3.对象操作流",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/day15-IO03%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C%E6%B5%81.html",
      "relativePath": "java/javaSEBase/day15-IO03对象操作流.md",
      "key": "v-20d60fe0",
      "path": "/java/javaSEBase/day15-IO03%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C%E6%B5%81.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1对象序列化流【应用】",
          "slug": "_3-1对象序列化流【应用】"
        },
        {
          "level": 2,
          "title": "3.2对象反序列化流【应用】",
          "slug": "_3-2对象反序列化流【应用】"
        },
        {
          "level": 2,
          "title": "3.3serialVersionUID&transient【应用】",
          "slug": "_3-3serialversionuid-transient【应用】"
        },
        {
          "level": 2,
          "title": "3.4对象操作流练习【应用】",
          "slug": "_3-4对象操作流练习【应用】"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "4.Properties集合",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/day15-IO04Properties%E9%9B%86%E5%90%88.html",
      "relativePath": "java/javaSEBase/day15-IO04Properties集合.md",
      "key": "v-28c21038",
      "path": "/java/javaSEBase/day15-IO04Properties%E9%9B%86%E5%90%88.html",
      "headers": [
        {
          "level": 2,
          "title": "4.1Properties作为Map集合的使用【应用】",
          "slug": "_4-1properties作为map集合的使用【应用】"
        },
        {
          "level": 2,
          "title": "4.2Properties作为Map集合的特有方法【应用】",
          "slug": "_4-2properties作为map集合的特有方法【应用】"
        },
        {
          "level": 2,
          "title": "4.3Properties和IO流相结合的方法【应用】",
          "slug": "_4-3properties和io流相结合的方法【应用】"
        },
        {
          "level": 2,
          "title": "4.4Properties集合练习【应用】",
          "slug": "_4-4properties集合练习【应用】"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "反射(reflect)",
      "frontmatter": {},
      "regularPath": "/java/javaSEBase/java.html",
      "relativePath": "java/javaSEBase/java.md",
      "key": "v-6c85b54c",
      "path": "/java/javaSEBase/java.html",
      "headers": [
        {
          "level": 2,
          "title": "四则运算案例",
          "slug": "四则运算案例"
        },
        {
          "level": 3,
          "title": "客户端的实现",
          "slug": "客户端的实现"
        },
        {
          "level": 3,
          "title": "代码执行时序图",
          "slug": "代码执行时序图"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "xpath解析xml文档",
      "frontmatter": {},
      "regularPath": "/java/java%E5%B7%A5%E5%85%B7/xpath%E8%A7%A3%E6%9E%90doc.html",
      "relativePath": "java/java工具/xpath解析doc.md",
      "key": "v-194bb9b2",
      "path": "/java/java%E5%B7%A5%E5%85%B7/xpath%E8%A7%A3%E6%9E%90doc.html",
      "headers": [
        {
          "level": 2,
          "title": "step1)导入maven坐标",
          "slug": "step1-导入maven坐标"
        },
        {
          "level": 2,
          "title": "step2)编写xml文件",
          "slug": "step2-编写xml文件"
        },
        {
          "level": 2,
          "title": "step3)编写解析文档方法",
          "slug": "step3-编写解析文档方法"
        }
      ],
      "lastUpdated": "8/5/2023, 10:41:09 PM",
      "lastUpdatedTimestamp": 1691304069000
    },
    {
      "title": "mybatis-pius使用多数据源",
      "frontmatter": {},
      "regularPath": "/java/mybatis_plus/03%E5%A4%9A%E6%95%B0%E6%8D%AE%E5%BA%93%E6%BA%90%E7%9A%84%E7%BC%96%E5%86%99.html",
      "relativePath": "java/mybatis_plus/03多数据库源的编写.md",
      "key": "v-fde39bb2",
      "path": "/java/mybatis_plus/03%E5%A4%9A%E6%95%B0%E6%8D%AE%E5%BA%93%E6%BA%90%E7%9A%84%E7%BC%96%E5%86%99.html",
      "headers": [
        {
          "level": 2,
          "title": "数据准备",
          "slug": "数据准备"
        },
        {
          "level": 3,
          "title": "数据库sql",
          "slug": "数据库sql"
        },
        {
          "level": 2,
          "title": "ex1)mybatis-plus简单查询",
          "slug": "ex1-mybatis-plus简单查询"
        },
        {
          "level": 3,
          "title": "导入依赖",
          "slug": "导入依赖"
        },
        {
          "level": 3,
          "title": "01)书写配置文件：",
          "slug": "_01-书写配置文件"
        },
        {
          "level": 3,
          "title": "02)创建pojo对象",
          "slug": "_02-创建pojo对象"
        },
        {
          "level": 3,
          "title": "03)创建Mapper接口",
          "slug": "_03-创建mapper接口"
        },
        {
          "level": 3,
          "title": "04)编写测试类",
          "slug": "_04-编写测试类"
        },
        {
          "level": 3,
          "title": "05)编写controller类",
          "slug": "_05-编写controller类"
        },
        {
          "level": 2,
          "title": "ex2)mybatis-plus多数据源",
          "slug": "ex2-mybatis-plus多数据源"
        },
        {
          "level": 3,
          "title": "01)导入依赖",
          "slug": "_01-导入依赖"
        },
        {
          "level": 3,
          "title": "02)修改配置文件",
          "slug": "_02-修改配置文件"
        },
        {
          "level": 3,
          "title": "03)编写controller",
          "slug": "_03-编写controller"
        },
        {
          "level": 3,
          "title": "04)指定数据源",
          "slug": "_04-指定数据源"
        },
        {
          "level": 3,
          "title": "05)多数据源验证",
          "slug": "_05-多数据源验证"
        },
        {
          "level": 3,
          "title": "06)@DS怎么使用",
          "slug": "_06-ds怎么使用"
        },
        {
          "level": 2,
          "title": "业务需求一：",
          "slug": "业务需求一"
        },
        {
          "level": 3,
          "title": "问题一：",
          "slug": "问题一"
        }
      ],
      "lastUpdated": "8/13/2023, 5:04:48 AM",
      "lastUpdatedTimestamp": 1691931888000
    },
    {
      "title": "网关入门快速搭建",
      "frontmatter": {},
      "regularPath": "/java/springcloudgateway/01gateway.html",
      "relativePath": "java/springcloudgateway/01gateway.md",
      "key": "v-3bb47468",
      "path": "/java/springcloudgateway/01gateway.html",
      "headers": [
        {
          "level": 2,
          "title": "第一步：创建父工程",
          "slug": "第一步-创建父工程"
        },
        {
          "level": 2,
          "title": "第二步：创建网关子项目",
          "slug": "第二步-创建网关子项目"
        },
        {
          "level": 3,
          "title": "导入依赖",
          "slug": "导入依赖"
        },
        {
          "level": 3,
          "title": "书写配置文件",
          "slug": "书写配置文件"
        },
        {
          "level": 2,
          "title": "第三步：创建user子项目",
          "slug": "第三步-创建user子项目"
        },
        {
          "level": 3,
          "title": "导入依赖",
          "slug": "导入依赖-2"
        },
        {
          "level": 3,
          "title": "书写配置文件",
          "slug": "书写配置文件-2"
        },
        {
          "level": 3,
          "title": "编写Controller",
          "slug": "编写controller"
        },
        {
          "level": 2,
          "title": "测试",
          "slug": "测试"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "ip地址是怎么划分的呢",
      "frontmatter": {},
      "regularPath": "/network/network01.html",
      "relativePath": "network/network01.md",
      "key": "v-40d90282",
      "path": "/network/network01.html",
      "headers": [
        {
          "level": 2,
          "title": "01）什么是ip地址",
          "slug": "_01-什么是ip地址"
        },
        {
          "level": 2,
          "title": "02）什么是子网划分",
          "slug": "_02-什么是子网划分"
        },
        {
          "level": 2,
          "title": "03）IP地址的类型划分",
          "slug": "_03-ip地址的类型划分"
        },
        {
          "level": 2,
          "title": "04）不同类型的地址范围是多少个",
          "slug": "_04-不同类型的地址范围是多少个"
        },
        {
          "level": 2,
          "title": "05）私有地址怎么分",
          "slug": "_05-私有地址怎么分"
        }
      ],
      "lastUpdated": "7/28/2023, 8:49:57 AM",
      "lastUpdatedTimestamp": 1690562997000
    },
    {
      "title": "开始掌握docsify",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/01docsify.html",
      "relativePath": "软件资源/01docsify.md",
      "key": "v-557ebcd4",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/01docsify.html",
      "headers": [
        {
          "level": 2,
          "title": "Quick start快速掌握",
          "slug": "quick-start快速掌握"
        },
        {
          "level": 3,
          "title": "Initialize(初始化)",
          "slug": "initialize-初始化"
        },
        {
          "level": 3,
          "title": "Writing content(写内容)",
          "slug": "writing-content-写内容"
        },
        {
          "level": 3,
          "title": "Preview your site(预览您的网站)",
          "slug": "preview-your-site-预览您的网站"
        },
        {
          "level": 3,
          "title": "Manual initialization(手动初始化)",
          "slug": "manual-initialization-手动初始化"
        },
        {
          "level": 2,
          "title": "Loading dialog(加载对话框)",
          "slug": "loading-dialog-加载对话框"
        },
        {
          "level": 2,
          "title": "Writing more pages(写更多的页面)",
          "slug": "writing-more-pages-写更多的页面"
        },
        {
          "level": 3,
          "title": "Sidebar(侧边栏,工具条)",
          "slug": "sidebar-侧边栏-工具条"
        },
        {
          "level": 3,
          "title": "Nested Sidebars（嵌套提要栏）",
          "slug": "nested-sidebars-嵌套提要栏"
        },
        {
          "level": 3,
          "title": "Set Page Titles from Sidebar Selection（设置页面标题从提要栏选择）",
          "slug": "set-page-titles-from-sidebar-selection-设置页面标题从提要栏选择"
        },
        {
          "level": 3,
          "title": "Table of Contents（目录）",
          "slug": "table-of-contents-目录"
        },
        {
          "level": 3,
          "title": "Ignoring Subheaders（忽略子标题）",
          "slug": "ignoring-subheaders-忽略子标题"
        },
        {
          "level": 2,
          "title": "HTML",
          "slug": "html"
        },
        {
          "level": 2,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 2,
          "title": "Nesting(嵌套)",
          "slug": "nesting-嵌套"
        },
        {
          "level": 2,
          "title": "Combining custom navbars with the emoji plugin(将自定义导航栏与表情符号插件相结合)",
          "slug": "combining-custom-navbars-with-the-emoji-plugin-将自定义导航栏与表情符号插件相结合"
        },
        {
          "level": 2,
          "title": "Basic usage(基本用法)",
          "slug": "basic-usage-基本用法"
        },
        {
          "level": 2,
          "title": "Custom background(自定义背景)",
          "slug": "custom-background-自定义背景"
        },
        {
          "level": 2,
          "title": "Coverpage as homepage(首页封面)",
          "slug": "coverpage-as-homepage-首页封面"
        },
        {
          "level": 2,
          "title": "Multiple covers(多个封面)",
          "slug": "multiple-covers-多个封面"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "英语语法",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/English_syntax.html",
      "relativePath": "软件资源/English_syntax.md",
      "key": "v-63361320",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/English_syntax.html",
      "headers": [
        {
          "level": 2,
          "title": "名词",
          "slug": "名词"
        },
        {
          "level": 3,
          "title": "不可数名词",
          "slug": "不可数名词"
        },
        {
          "level": 2,
          "title": "定语&状语",
          "slug": "定语-状语"
        },
        {
          "level": 2,
          "title": "01）When/While引导时间状语从句",
          "slug": "_01-when-while引导时间状语从句"
        },
        {
          "level": 3,
          "title": "用while情况",
          "slug": "用while情况"
        },
        {
          "level": 3,
          "title": "即可用when/while情况",
          "slug": "即可用when-while情况"
        },
        {
          "level": 3,
          "title": "用when情况",
          "slug": "用when情况"
        },
        {
          "level": 3,
          "title": "练习",
          "slug": "练习"
        },
        {
          "level": 2,
          "title": "02）a little/a bit",
          "slug": "_02-a-little-a-bit"
        },
        {
          "level": 3,
          "title": "案例",
          "slug": "案例"
        },
        {
          "level": 3,
          "title": "练习",
          "slug": "练习-2"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "导航栏设置",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/02top%E5%AF%BC%E8%88%AA%E6%A0%8F%E7%9A%84%E8%AE%BE%E7%BD%AE.html",
      "relativePath": "软件资源/vuepress怎么玩/02top导航栏的设置.md",
      "key": "v-4dbdaeb8",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/02top%E5%AF%BC%E8%88%AA%E6%A0%8F%E7%9A%84%E8%AE%BE%E7%BD%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "配置logo",
          "slug": "配置logo"
        },
        {
          "level": 2,
          "title": "配置样式案例：",
          "slug": "配置样式案例"
        }
      ]
    },
    {
      "title": "vuepress标体设置规则",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/SetTitle.html",
      "relativePath": "软件资源/vuepress怎么玩/SetTitle.md",
      "key": "v-8ba33ae4",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/SetTitle.html",
      "headers": [
        {
          "level": 2,
          "title": "01）标题级别怎么搞！",
          "slug": "_01-标题级别怎么搞"
        },
        {
          "level": 2,
          "title": "02）怎么搞如下效果呢？",
          "slug": "_02-怎么搞如下效果呢"
        },
        {
          "level": 2,
          "title": "03）编写代码",
          "slug": "_03-编写代码"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "vuepress常用语法",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/Writing_rules.html",
      "relativePath": "软件资源/vuepress怎么玩/Writing_rules.md",
      "key": "v-021585d8",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/vuepress%E6%80%8E%E4%B9%88%E7%8E%A9/Writing_rules.html",
      "headers": [
        {
          "level": 2,
          "title": "01）提示块",
          "slug": "_01-提示块"
        },
        {
          "level": 2,
          "title": "02）提示块自定义标题",
          "slug": "_02-提示块自定义标题"
        },
        {
          "level": 2,
          "title": "03)字标粗&字标颜色",
          "slug": "_03-字标粗-字标颜色"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    },
    {
      "title": "30岁以后，一定要懂的《滕王阁序》",
      "frontmatter": {},
      "regularPath": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90.html",
      "relativePath": "软件资源/软件资源.md",
      "key": "v-04d9f279",
      "path": "/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90/%E8%BD%AF%E4%BB%B6%E8%B5%84%E6%BA%90.html",
      "headers": [
        {
          "level": 2,
          "title": "懂诗词歌赋",
          "slug": "懂诗词歌赋"
        }
      ],
      "lastUpdated": "7/29/2023, 7:51:28 AM",
      "lastUpdatedTimestamp": 1690645888000
    },
    {
      "title": "强制关闭端口号",
      "frontmatter": {},
      "regularPath": "/%E8%BF%90%E7%BB%B4/windows/cmd.html",
      "relativePath": "运维/windows/cmd.md",
      "key": "v-34a4cb9c",
      "path": "/%E8%BF%90%E7%BB%B4/windows/cmd.html",
      "headers": [
        {
          "level": 2,
          "title": "强制关闭端口号",
          "slug": "强制关闭端口号"
        },
        {
          "level": 2,
          "title": "windows文件不能删除",
          "slug": "windows文件不能删除"
        },
        {
          "level": 3,
          "title": "什么意思？",
          "slug": "什么意思"
        },
        {
          "level": 3,
          "title": "符号表示什么意思？",
          "slug": "符号表示什么意思"
        },
        {
          "level": 3,
          "title": "都是什么单词缩写？",
          "slug": "都是什么单词缩写"
        }
      ],
      "lastUpdated": "8/5/2023, 7:39:15 AM",
      "lastUpdatedTimestamp": 1691249955000
    }
  ],
  "themeConfig": {
    "logo": "logo.svg",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "图南的博客",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/triggergun"
          },
          {
            "text": "知乎",
            "link": "https://www.zhihu.com/people/hong-lang-80-78/posts"
          }
        ]
      },
      {
        "text": "git",
        "link": "/git/git"
      },
      {
        "text": "运维",
        "items": [
          {
            "text": "命令",
            "link": "/运维/windows/cmd"
          },
          {
            "text": "网络",
            "link": "/network/network01"
          }
        ]
      },
      {
        "text": "java",
        "items": [
          {
            "text": "java基础",
            "link": "/java/javaSEBase/java"
          },
          {
            "text": "dao层框架",
            "items": [
              {
                "text": "mybatis",
                "link": "/java/Mybatis/mybatis"
              },
              {
                "text": "mybatis-plus",
                "link": "/java/mybatis_plus/03%E5%A4%9A%E6%95%B0%E6%8D%AE%E5%BA%93%E6%BA%90%E7%9A%84%E7%BC%96%E5%86%99"
              }
            ]
          },
          {
            "text": "springCloud",
            "items": [
              {
                "text": "gateway",
                "link": "/java/springcloudgateway/01gateway"
              }
            ]
          },
          {
            "text": "设计模式",
            "link": "/java/designModel/AssemblerDesignPattern"
          },
          {
            "text": "java工具",
            "link": "/java/java%E5%B7%A5%E5%85%B7/xpath%E8%A7%A3%E6%9E%90doc"
          }
        ]
      }
    ],
    "sidebar": {
      "/软件资源/": [
        {
          "title": "软件资源",
          "collapsable": false,
          "children": [
            "/软件资源/软件资源",
            "/软件资源/English_syntax"
          ]
        },
        {
          "title": "docsify",
          "collapsable": false,
          "children": [
            "/软件资源/01docsify"
          ]
        },
        {
          "title": "vuepress语法",
          "collapsable": false,
          "children": [
            "/软件资源/vuepress怎么玩/SetTitle",
            "/软件资源/vuepress怎么玩/Writing_rules",
            "/软件资源/vuepress怎么玩/02top导航栏的设置"
          ]
        }
      ],
      "/git/": [
        {
          "title": "git",
          "collapsable": false,
          "children": [
            "/git/git"
          ]
        },
        {
          "title": "本地仓库提交到git",
          "collapsable": false,
          "children": [
            "/git/git推送到远程的仓库"
          ]
        }
      ],
      "/运维/windows/": [
        {
          "title": "windows运维",
          "collapsable": false,
          "children": [
            "/运维/windows/cmd"
          ]
        }
      ],
      "/network/": [
        {
          "title": "ip地址说起",
          "collapsable": false,
          "children": [
            "/network/network01"
          ]
        }
      ],
      "/java/Mybatis/": [
        {
          "title": "mybatis整合springboot",
          "collapsable": false,
          "children": [
            "/java/Mybatis/mybatis"
          ]
        },
        {
          "title": "查询",
          "collapsable": false,
          "children": [
            "/java/Mybatis/select01",
            "/java/Mybatis/select02"
          ]
        }
      ],
      "/java/mybatis_plus/": [
        {
          "title": "mybatis-pius使用多数据源",
          "collapsable": true,
          "children": [
            "/java/mybatis_plus/03多数据库源的编写"
          ]
        }
      ],
      "/java/javaSEBase/": [
        {
          "title": "java基础案例",
          "collapsable": false,
          "children": [
            "/java/javaSEBase/java"
          ]
        },
        {
          "title": "java-IO",
          "collapsable": false,
          "children": [
            "/java/javaSEBase/day14-IO",
            "/java/javaSEBase/day15-IO01流",
            "/java/javaSEBase/day15-IO02转换流",
            "/java/javaSEBase/day15-IO03对象操作流",
            "/java/javaSEBase/day15-IO04Properties集合"
          ]
        }
      ],
      "/java/springcloudgateway/": [
        {
          "title": "springCloud-Gateway",
          "collapsable": false,
          "children": [
            "/java/springcloudgateway/01gateway"
          ]
        }
      ],
      "/java/designModel/": [
        {
          "title": "design",
          "collapsable": false,
          "children": [
            "/java/designModel/AssemblerDesignPattern",
            "/java/designModel/02%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F"
          ]
        }
      ],
      "/java/java工具/": [
        {
          "title": "java常用工具库",
          "collapsable": false,
          "children": [
            "/java/java%E5%B7%A5%E5%85%B7/xpath%E8%A7%A3%E6%9E%90doc"
          ]
        }
      ]
    },
    "lastUpdated": "Last Updated",
    "extraWatchFiles": [
      ".vuepress/config.js"
    ]
  }
}